"""fixed fields for kids and employees tables

Revision ID: aad867a4cc7b
Revises: fca018da8d4e
Create Date: 2024-08-07 14:32:15.888291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad867a4cc7b'
down_revision: Union[str, None] = 'fca018da8d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
